package com.thoughtworks.sbtApiMappings

import scala.io.Source
import org.scalatest.matchers.should.Matchers
import org.scalatest.wordspec.AnyWordSpec

class BootstrapApiMappingsSpec extends AnyWordSpec with Matchers {
  "BootstrapSbtApiMappings" should {
    "provide a working default bootstrapJavadocURL including java.lang package" in {
      val src = Source.fromURL(raw"${BootstrapApiMappings.defaultBootstrapJavadocUrl}java/lang/package-summary.html")
      try {
        src.take(200).mkString should include("Generated by javadoc")
      } finally {
        src.close()
      }
    }
  }
}
