package com.thoughtworks.sbtApiMappings

import scala.io.Source
import org.scalatest.matchers.should.Matchers
import org.scalatest.wordspec.AnyWordSpec

class BootstrapApiMappingsSpec extends AnyWordSpec with Matchers {
  "BootstrapSbtApiMappings" should {
    "provide a working default bootstrapJavadocURL" in {
      val src = Source.fromURL(BootstrapApiMappings.defaultBootstrapJavadocUrl)
      src.take(200).mkString should include("Generated by javadoc")
      src.close()
    }
  }
}
