package com.thoughtworks.sbtApiMappings

import scala.io.Source
import org.scalatest.{ WordSpec, Matchers }

class BootstrapApiMappingsSpec extends WordSpec with Matchers {
  "BootstrapSbtApiMappings" should {
    "provide a working default bootstrapJavadocURL" in {
      val src = Source.fromURL(BootstrapApiMappings.defaultBootstrapJavadocUrl)
      src.take(200).mkString should include("Generated by javadoc")
      src.close()
    }
  }
}
